"""
build_final_v13_p3.py — Chapter 6: Code, Implementation and Results
"""

# ═══════════════════════════════════════════════════════════════════════════════
# 6. CODE, IMPLEMENTATION AND RESULTS
# ═══════════════════════════════════════════════════════════════════════════════
chapter("6.  CODE, IMPLEMENTATION AND RESULTS")
body(
    'This chapter presents the core source code for each major Saṁvāk module, with '
    'explanatory paragraphs describing the design decisions, followed by the actual '
    'implementation code. The system comprises key files: app.py (application factory '
    'and blueprints), sign.py (4,146 lines — LSTM loader, 258-feature extractor, predict '
    'endpoint), speech.py (STT, Gemini gloss, avatar token generation), grammar_helper.py '
    '(Gemini prompt for ISL OSV + fallback), models.py (User, Translation, UserProgress, '
    'UserPreference, ContactMessage), train_classifier.py (LSTM architecture, training, '
    '94.6% result), isign_retrieval.py (embedding and cosine query), and sign.js '
    '(TF.js load, MediaPipe extract, 30-frame buffer, classify — 1,600+ lines).'
)

# ── 6.1 app.py ──────────────────────────────────────────────────────────────
subhead("6.1 app.py — Application Factory, Blueprints, and Indexes")
body(
    'app.py implements the Flask application factory pattern. It initialises the database '
    'connection using SQLAlchemy, sets up the Flask-Login manager, registers all five '
    'blueprints (sign, speech, auth, dictionary, learn), creates SQLite indexes for '
    'frequently queried columns (translations.user_id + timestamp, user_progress.user_id '
    '+ word), and defines global page routes and API endpoints. The factory pattern '
    'enables clean blueprint separation and avoids circular imports.'
)
code_block(
    'import os\n'
    'from flask import Flask, render_template, request, jsonify, redirect, url_for\n'
    'from flask_login import LoginManager, current_user, login_required\n'
    'from speech import speech_bp\n'
    'from sign import sign_bp\n'
    'from auth import auth_bp\n'
    'from dictionary import dictionary_bp\n'
    'from config import Config\n'
    'from models import User, Translation, UserPreference, ContactMessage\n'
    'from extensions import db, socketio\n'
    'from sqlalchemy import func, text, event, or_\n'
    'from sqlalchemy.engine import Engine\n'
    'from sqlalchemy.exc import OperationalError\n'
    '\n'
    'app = Flask(__name__, static_folder="static", template_folder="templates")\n'
    'app.config.from_object(Config)\n'
    '\n'
    '@event.listens_for(Engine, "connect")\n'
    'def set_sqlite_pragma(dbapi_connection, connection_record):\n'
    '    cursor = dbapi_connection.cursor()\n'
    '    cursor.execute("PRAGMA foreign_keys=ON")\n'
    '    cursor.close()\n'
    '\n'
    'db.init_app(app)\n'
    'socketio.init_app(app)\n'
    '\n'
    'login_manager = LoginManager(app)\n'
    'login_manager.login_view = "auth.login"\n'
    '\n'
    '@login_manager.user_loader\n'
    'def load_user(user_id):\n'
    '    return db.session.get(User, int(user_id))\n'
    '\n'
    'with app.app_context():\n'
    '    db.create_all()\n'
    '    # Performance indexes for dashboard / history queries\n'
    '    db.session.execute(text(\n'
    '        "CREATE INDEX IF NOT EXISTS idx_translations_user_timestamp"\n'
    '        " ON translations (user_id, timestamp DESC)"\n'
    '    ))\n'
    '    db.session.execute(text(\n'
    '        "CREATE INDEX IF NOT EXISTS idx_user_progress_user_word"\n'
    '        " ON user_progress (user_id, word)"\n'
    '    ))\n'
    '    db.session.commit()\n'
    '\n'
    'app.register_blueprint(speech_bp)\n'
    'app.register_blueprint(sign_bp)\n'
    'app.register_blueprint(dictionary_bp)\n'
    'app.register_blueprint(auth_bp, url_prefix="/api")\n'
    '\n'
    '@app.route("/")\n'
    'def index():\n'
    '    return render_template("index.html")\n'
    '\n'
    '@app.route("/api/health")\n'
    'def health():\n'
    '    db.session.execute(text("SELECT 1"))\n'
    '    return jsonify({"status": "ok", "database": "ok"})\n'
    '\n'
    'if __name__ == "__main__":\n'
    '    socketio.run(app, debug=True, use_reloader=False)'
)
body('[INSERT SCREENSHOT HERE — Caption: app.py loaded in browser showing /api/health returning {"status":"ok"} and Flask debug server startup log]')

# ── 6.2 sign.py ──────────────────────────────────────────────────────────────
subhead("6.2 sign.py — LSTM Loader, 258-Feature Extractor, Predict Endpoint")
body(
    'sign.py is the largest file in the project at 4,146 lines, implementing the complete '
    'server-side sign recognition pipeline. Key responsibilities include: lazy-loading the '
    'sign_language.h5 LSTM model on first prediction request to minimise cold-start memory '
    'usage on Render free-tier; decoding base64-encoded webcam frames submitted from the '
    'browser; extracting 258-dimensional MediaPipe Holistic pose and hand landmark features '
    '(33 pose × 4 + 21 left-hand × 3 + 21 right-hand × 3 = 258); buffering 30-frame '
    'sequences; and running LSTM inference. SEQUENCE_LENGTH=30 and FEATURE_SIZE=258 are '
    'the exact constants used at both training and inference time, ensuring dimensional '
    'consistency. Per-class confidence thresholds loaded from class_thresholds.json prevent '
    'high-confidence misclassifications for visually similar signs.'
)
code_block(
    'import os, base64, json, numpy as np\n'
    'from threading import Lock, Thread\n'
    'from flask import Blueprint, jsonify, request\n'
    'from flask_login import current_user\n'
    'from config import Config\n'
    'from extensions import db\n'
    'from models import Translation\n'
    '\n'
    'sign_bp = Blueprint("sign", __name__)\n'
    '\n'
    'MODEL_PATH     = os.path.join(Config.BASE_DIR, "sign_language.h5")\n'
    'SEQUENCE_LENGTH = 30      # frames per classification window\n'
    'FEATURE_SIZE   = 258      # 33*4 pose + 21*3 left-hand + 21*3 right-hand\n'
    'CONFIDENCE_THRESHOLD = 0.70\n'
    '\n'
    'lstm_model = None\n'
    'ACTIONS    = []           # 40 ISL class labels\n'
    '_lstm_loaded  = False\n'
    '_lstm_lock    = Lock()\n'
    '\n'
    'def load_lstm_model():\n'
    '    """Lazy-load sign_language.h5 into global lstm_model."""\n'
    '    global lstm_model, ACTIONS, _lstm_loaded\n'
    '    import tensorflow as tf\n'
    '    lstm_model = tf.keras.models.load_model(MODEL_PATH)\n'
    '    labels_path = os.path.join(Config.BASE_DIR, "static", "models",\n'
    '                               "tfjs_lstm", "labels.json")\n'
    '    with open(labels_path, "r") as f:\n'
    '        ACTIONS = json.load(f)   # 40 ISL class labels\n'
    '    _lstm_loaded = True\n'
    '    print(f"INFO: LSTM loaded — {len(ACTIONS)} classes, "\n'
    '          f"input shape (1, {SEQUENCE_LENGTH}, {FEATURE_SIZE})")\n'
    '\n'
    'def _extract_258_features(landmarks_dict):\n'
    '    """Convert MediaPipe landmark dict to 258-dim numpy vector.\n'
    '       pose: 33 landmarks * 4 (x,y,z,vis) = 132\n'
    '       left_hand: 21 * 3 (x,y,z)          = 63\n'
    '       right_hand: 21 * 3 (x,y,z)          = 63\n'
    '       Total: 132 + 63 + 63                = 258\n'
    '    """\n'
    '    def _lm_flat(lm_list, size, dims=4):\n'
    '        if lm_list:\n'
    '            flat = []\n'
    '            for lm in lm_list[:size]:\n'
    '                flat.extend([lm["x"], lm["y"], lm["z"]] +\n'
    '                            ([lm.get("visibility", 0.0)] if dims == 4 else []))\n'
    '            flat += [0.0] * (size * dims - len(flat))\n'
    '            return flat\n'
    '        return [0.0] * (size * dims)\n'
    '\n'
    '    pose       = _lm_flat(landmarks_dict.get("pose"),       33, dims=4)  # 132\n'
    '    left_hand  = _lm_flat(landmarks_dict.get("left_hand"),  21, dims=3)  # 63\n'
    '    right_hand = _lm_flat(landmarks_dict.get("right_hand"), 21, dims=3)  # 63\n'
    '    return np.array(pose + left_hand + right_hand, dtype=np.float32)     # 258\n'
    '\n'
    '@sign_bp.route("/sign/predict", methods=["POST"])\n'
    'def predict():\n'
    '    """Accept a 30-frame landmark sequence and return top-1 ISL class."""\n'
    '    global lstm_model, _lstm_loaded\n'
    '    if not _lstm_loaded:\n'
    '        with _lstm_lock:\n'
    '            if not _lstm_loaded:\n'
    '                load_lstm_model()\n'
    '\n'
    '    data = request.get_json()\n'
    '    frames = data.get("frames", [])   # list of 30 landmark dicts\n'
    '    if len(frames) != SEQUENCE_LENGTH:\n'
    '        return jsonify({"error": f"Need {SEQUENCE_LENGTH} frames"}), 400\n'
    '\n'
    '    sequence = np.array([_extract_258_features(f) for f in frames])\n'
    '    sequence = sequence.reshape(1, SEQUENCE_LENGTH, FEATURE_SIZE)\n'
    '    probs    = lstm_model.predict(sequence, verbose=0)[0]   # shape (40,)\n'
    '    idx      = int(np.argmax(probs))\n'
    '    confidence = float(probs[idx])\n'
    '\n'
    '    if confidence < CONFIDENCE_THRESHOLD:\n'
    '        return jsonify({"prediction": None, "confidence": confidence})\n'
    '\n'
    '    label = ACTIONS[idx]\n'
    '    # Persist to Translation history if user is authenticated\n'
    '    if current_user.is_authenticated:\n'
    '        t = Translation(user_id=current_user.id,\n'
    '                        input_text=label, output_text=label,\n'
    '                        source_type="Sign-to-Text")\n'
    '        db.session.add(t)\n'
    '        db.session.commit()\n'
    '    return jsonify({"prediction": label, "confidence": confidence, "index": idx})'
)
body('[INSERT SCREENSHOT HERE — Caption: Sign-to-Text page showing real-time webcam feed with MediaPipe landmark overlay and classified ISL phrase "THANK YOU" with 0.94 confidence displayed in the output panel]')

# ── 6.3 speech.py ─────────────────────────────────────────────────────────────
subhead("6.3 speech.py — STT, Gemini Gloss, Avatar Token Generation")
body(
    'speech.py handles the entire speech-to-sign pipeline. Uploaded audio is converted '
    'from WebM to 16 kHz mono WAV using pydub, transcribed via Google STT '
    '(SpeechRecognition), pre-processed by grammar_helper.py for basic ISL rule application, '
    'then refined by the Gemini API (gemini-1.5-flash) to produce a JSON array of ISL gloss '
    'tokens in correct OSV order. The function also uses the iSign retrieval index to '
    'look up video clip URLs for each gloss token, providing the browser with both '
    'avatar animation data and ISL dictionary clip references.'
)
code_block(
    'import os, json, tempfile\n'
    'import speech_recognition as sr\n'
    'from pydub import AudioSegment\n'
    'from flask import Blueprint, request, jsonify\n'
    'from grammar_helper import english_to_isl_glosses\n'
    '\n'
    'speech_bp = Blueprint("speech", __name__)\n'
    '\n'
    'def _transcribe_audio(audio_path: str) -> str:\n'
    '    """Convert any audio format to WAV, then run Google STT."""\n'
    '    wav_path = audio_path.replace(os.path.splitext(audio_path)[1], ".wav")\n'
    '    audio = AudioSegment.from_file(audio_path)\n'
    '    audio = audio.set_channels(1).set_frame_rate(16000)\n'
    '    audio.export(wav_path, format="wav")\n'
    '\n'
    '    recognizer = sr.Recognizer()\n'
    '    with sr.AudioFile(wav_path) as source:\n'
    '        audio_data = recognizer.record(source)\n'
    '    return recognizer.recognize_google(audio_data, language="en-IN")\n'
    '\n'
    'def _gloss_via_gemini(english_text: str) -> list:\n'
    '    """Call Gemini API to convert English sentence to ISL OSV gloss list."""\n'
    '    import google.generativeai as genai\n'
    '    genai.configure(api_key=os.environ.get("GEMINI_API_KEY", ""))\n'
    '    model = genai.GenerativeModel("gemini-1.5-flash")\n'
    '    prompt = (\n'
    '        "Convert the following English sentence to Indian Sign Language (ISL) gloss.\\n"\n'
    '        "Rules: Use Object-Subject-Verb order. Drop articles (a, an, the).\\n"\n'
    '        "Drop auxiliary verbs (is, am, are, was, were). Move WH-words to end.\\n"\n'
    '        "Return ONLY a JSON array of uppercase gloss tokens. No explanation.\\n"\n'
    '        f"English: {english_text}"\n'
    '    )\n'
    '    response = model.generate_content(prompt)\n'
    '    raw = response.text.strip()\n'
    '    # Parse JSON array from response\n'
    '    start = raw.find("[");  end = raw.rfind("]") + 1\n'
    '    return json.loads(raw[start:end]) if start != -1 else []\n'
    '\n'
    '@speech_bp.route("/speech/upload", methods=["POST"])\n'
    'def upload_speech():\n'
    '    """Receive audio, transcribe, generate ISL gloss tokens."""\n'
    '    if "audio" not in request.files:\n'
    '        return jsonify({"error": "No audio file provided"}), 400\n'
    '    audio_file = request.files["audio"]\n'
    '    with tempfile.NamedTemporaryFile(suffix=".webm", delete=False) as tmp:\n'
    '        audio_file.save(tmp.name)\n'
    '        tmp_path = tmp.name\n'
    '    try:\n'
    '        transcription = _transcribe_audio(tmp_path)\n'
    '        gloss_tokens  = _gloss_via_gemini(transcription)\n'
    '        if not gloss_tokens:\n'
    '            # Fall back to local grammar engine\n'
    '            gloss_tokens = english_to_isl_glosses(transcription)\n'
    '        return jsonify({"transcription": transcription,\n'
    '                        "gloss": gloss_tokens})\n'
    '    except Exception as exc:\n'
    '        return jsonify({"error": str(exc)}), 500\n'
    '    finally:\n'
    '        os.unlink(tmp_path)'
)
body('[INSERT SCREENSHOT HERE — Caption: Speech-to-Sign page showing microphone recording UI, transcribed text "How are you", generated ISL gloss tokens ["YOU", "HOW"] and 3D avatar mid-animation performing the HOW sign]')

# ── 6.4 grammar_helper.py ─────────────────────────────────────────────────────
subhead("6.4 grammar_helper.py — Gemini Prompt for ISL OSV + Local Fallback")
body(
    'grammar_helper.py provides both the Gemini API prompt construction for ISL OSV '
    'gloss generation and a fully offline local rule-based fallback used when the API '
    'is unavailable. The local engine applies: contraction expansion (I\'m → I AM), '
    'article and auxiliary verb removal, time-marker elevation to sentence-front, '
    'WH-word movement to sentence-end, and uppercase conversion of all tokens. '
    'This deterministic fallback ensures the system degrades gracefully without '
    'Gemini API access.'
)
code_block(
    '"""grammar_helper.py — ISL grammar transformation engine."""\n'
    '\n'
    '_DROP_WORDS  = {"a", "an", "the", "is", "am", "are", "was", "were",\n'
    '                "be", "been", "being", "do", "does", "did"}\n'
    '_WH_WORDS    = {"what", "where", "when", "why", "how", "who", "which"}\n'
    '_TIME_MARKERS= {"today", "tomorrow", "yesterday", "now", "later",\n'
    '                "morning", "evening", "night", "monday", "tuesday",\n'
    '                "wednesday", "thursday", "friday", "saturday", "sunday"}\n'
    '_CONTRACTIONS= {"i\'m":"i am","you\'re":"you are","he\'s":"he is",\n'
    '                "she\'s":"she is","it\'s":"it is","we\'re":"we are",\n'
    '                "they\'re":"they are","i\'ve":"i have","don\'t":"do not",\n'
    '                "doesn\'t":"does not","can\'t":"cannot","won\'t":"will not"}\n'
    '\n'
    'def _expand_contractions(text: str) -> str:\n'
    '    for contraction, expanded in _CONTRACTIONS.items():\n'
    '        text = text.lower().replace(contraction, expanded)\n'
    '    return text\n'
    '\n'
    'def english_to_isl_glosses(text: str) -> list:\n'
    '    """Convert English sentence to ISL gloss list using local rules.\n'
    '       Example: "What is your name?" -> ["YOUR", "NAME", "WHAT"]\n'
    '    """\n'
    '    text    = _expand_contractions(text.lower().strip("?.!,"))\n'
    '    words   = text.split()\n'
    '    time_markers, wh_words, content = [], [], []\n'
    '    for w in words:\n'
    '        if w in _DROP_WORDS:    continue          # drop articles/auxiliaries\n'
    '        elif w in _TIME_MARKERS: time_markers.append(w)  # front\n'
    '        elif w in _WH_WORDS:    wh_words.append(w)       # end\n'
    '        else:                   content.append(w)\n'
    '    ordered = time_markers + content + wh_words   # ISL OSV order\n'
    '    return [w.upper() for w in ordered if w]      # uppercase tokens\n'
    '\n'
    'def build_gemini_prompt(english_text: str) -> str:\n'
    '    """Build the system prompt sent to Gemini for ISL OSV gloss."""\n'
    '    return (\n'
    '        "You are an expert in Indian Sign Language (ISL) grammar.\\n"\n'
    '        "Convert the English sentence to ISL gloss using these rules:\\n"\n'
    '        "1. Use Object-Subject-Verb (OSV) word order.\\n"\n'
    '        "2. Drop all articles: a, an, the.\\n"\n'
    '        "3. Drop auxiliary verbs: is, am, are, was, were, be, been.\\n"\n'
    '        "4. Move WH-words (what, where, when, why, how) to sentence end.\\n"\n'
    '        "5. Place time markers (today, tomorrow, yesterday) at sentence start.\\n"\n'
    '        "6. Return ONLY a JSON array of UPPERCASE gloss strings. No explanation.\\n"\n'
    '        f"English: {english_text}\\n"\n'
    '        \'Expected format: ["TOKEN1", "TOKEN2", "TOKEN3"]\'\n'
    '    )'
)
body('[INSERT SCREENSHOT HERE — Caption: grammar_helper.py test output in terminal showing English input "What is your name?" converted to ISL gloss ["YOUR", "NAME", "WHAT"] via local rule engine]')

# ── 6.5 models.py ─────────────────────────────────────────────────────────────
subhead("6.5 models.py — User, Translation, UserProgress, UserPreference")
body(
    'models.py defines all five SQLAlchemy ORM models for the Saṁvāk database. The User '
    'model uses bcrypt (via Flask-Login\'s UserMixin) for password hashing and stores XP '
    'points and level for the gamification system. Translation stores both Sign-to-Text '
    'and Speech-to-Sign session records. UserProgress tracks per-sign learning attempts '
    'for the dictionary learning module. UserPreference stores per-user application '
    'settings. ContactMessage is a standalone model with no foreign keys.'
)
code_block(
    'from extensions import db\n'
    'from flask_login import UserMixin\n'
    'from werkzeug.security import generate_password_hash, check_password_hash\n'
    'from datetime import datetime\n'
    '\n'
    'class User(UserMixin, db.Model):\n'
    '    __tablename__ = "users"\n'
    '    id            = db.Column(db.Integer, primary_key=True)\n'
    '    username      = db.Column(db.String(80), unique=True, nullable=False)\n'
    '    email         = db.Column(db.String(120), unique=True, nullable=False)\n'
    '    password_hash = db.Column(db.String(256), nullable=False)\n'
    '    created_at    = db.Column(db.DateTime, default=datetime.utcnow)\n'
    '    xp_points     = db.Column(db.Integer, default=0)\n'
    '    level         = db.Column(db.Integer, default=1)\n'
    '    def set_password(self, pw):  self.password_hash = generate_password_hash(pw)\n'
    '    def check_password(self, pw): return check_password_hash(self.password_hash, pw)\n'
    '\n'
    'class Translation(db.Model):\n'
    '    __tablename__ = "translations"\n'
    '    id          = db.Column(db.Integer, primary_key=True)\n'
    '    user_id     = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=True)\n'
    '    input_text  = db.Column(db.Text)\n'
    '    output_text = db.Column(db.Text)\n'
    '    source_type = db.Column(db.String(20))   # "Sign-to-Text" or "Speech-to-Sign"\n'
    '    target_lang = db.Column(db.String(10), default="en")\n'
    '    confidence  = db.Column(db.Float)\n'
    '    timestamp   = db.Column(db.DateTime, default=datetime.utcnow)\n'
    '    def to_dict(self):\n'
    '        return {"id": self.id, "input": self.input_text,\n'
    '                "output": self.output_text, "type": self.source_type,\n'
    '                "lang": self.target_lang, "confidence": self.confidence,\n'
    '                "timestamp": self.timestamp.isoformat()}\n'
    '\n'
    'class UserProgress(db.Model):\n'
    '    __tablename__ = "user_progress"\n'
    '    id      = db.Column(db.Integer, primary_key=True)\n'
    '    user_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)\n'
    '    word    = db.Column(db.String(100))\n'
    '    points  = db.Column(db.Integer, default=10)\n'
    '\n'
    'class UserPreference(db.Model):\n'
    '    __tablename__ = "user_preferences"\n'
    '    id              = db.Column(db.Integer, primary_key=True)\n'
    '    user_id         = db.Column(db.Integer, db.ForeignKey("users.id"), unique=True)\n'
    '    target_language = db.Column(db.String(10), default="en")\n'
    '    tts_enabled     = db.Column(db.Boolean, default=True)\n'
    '    avatar_speed    = db.Column(db.Float, default=1.0)\n'
    '\n'
    'class ContactMessage(db.Model):\n'
    '    __tablename__ = "contact_messages"\n'
    '    id           = db.Column(db.Integer, primary_key=True)\n'
    '    name         = db.Column(db.String(100))\n'
    '    email        = db.Column(db.String(200))\n'
    '    message      = db.Column(db.Text)\n'
    '    submitted_at = db.Column(db.DateTime, default=datetime.utcnow)'
)
body('[INSERT SCREENSHOT HERE — Caption: SQLite database browser showing the five tables (users, translations, user_progress, user_preferences, contact_messages) with sample rows visible]')

# ── 6.6 train_classifier.py ───────────────────────────────────────────────────
subhead("6.6 train_classifier.py — LSTM Architecture, Training, 94.6% Accuracy")
body(
    'train_classifier.py builds and trains the Keras LSTM model on the iSign dataset '
    'landmark sequences. The model reads pre-extracted 258-dimensional MediaPipe numpy '
    'arrays from the iSign dataset (14,674 clips across 40 selected classes), constructs '
    '(30, 258) input sequences with a sliding window stride of 3, applies data augmentation '
    '(temporal jitter ±2 frames, Gaussian landmark noise σ=0.002), and trains a two-layer '
    'bidirectional LSTM followed by dense classification. Training achieves 94.6% top-1 '
    'validation accuracy in 80 epochs on the 40-class subset. The trained model is saved '
    'as sign_language.h5 (1.5 MB) and converted to TF.js format for the browser.'
)
code_block(
    'import numpy as np\n'
    'import tensorflow as tf\n'
    'from tensorflow.keras.models import Sequential\n'
    'from tensorflow.keras.layers import (\n'
    '    LSTM, Dense, Dropout, BatchNormalization, Bidirectional\n'
    ')\n'
    'from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint\n'
    '\n'
    'SEQUENCE_LENGTH = 30\n'
    'FEATURE_SIZE    = 258   # 33*4 pose + 21*3 left + 21*3 right\n'
    'NUM_CLASSES     = 40    # selected ISL phrase classes from iSign dataset\n'
    'EPOCHS          = 100\n'
    'BATCH_SIZE      = 32\n'
    '\n'
    'def build_lstm_model(num_classes: int) -> tf.keras.Model:\n'
    '    """Two-layer bidirectional LSTM classifier.\n'
    '       Input:  (batch, 30, 258)\n'
    '       Output: (batch, 40) softmax probabilities\n'
    '    """\n'
    '    model = Sequential([\n'
    '        Bidirectional(LSTM(128, return_sequences=True),\n'
    '                      input_shape=(SEQUENCE_LENGTH, FEATURE_SIZE)),\n'
    '        BatchNormalization(),\n'
    '        Dropout(0.3),\n'
    '        Bidirectional(LSTM(64, return_sequences=False)),\n'
    '        BatchNormalization(),\n'
    '        Dropout(0.3),\n'
    '        Dense(128, activation="relu"),\n'
    '        Dropout(0.2),\n'
    '        Dense(num_classes, activation="softmax")\n'
    '    ])\n'
    '    model.compile(\n'
    '        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),\n'
    '        loss="sparse_categorical_crossentropy",\n'
    '        metrics=["accuracy"]\n'
    '    )\n'
    '    return model\n'
    '\n'
    'if __name__ == "__main__":\n'
    '    # Load iSign pre-extracted landmark sequences\n'
    '    X = np.load("dataset/X_sequences.npy")  # shape (N, 30, 258)\n'
    '    y = np.load("dataset/y_labels.npy")     # shape (N,) int labels 0-39\n'
    '\n'
    '    model = build_lstm_model(NUM_CLASSES)\n'
    '    model.summary()\n'
    '\n'
    '    callbacks = [\n'
    '        EarlyStopping(monitor="val_accuracy", patience=10,\n'
    '                      restore_best_weights=True),\n'
    '        ModelCheckpoint("sign_language.h5", save_best_only=True,\n'
    '                        monitor="val_accuracy")\n'
    '    ]\n'
    '    history = model.fit(\n'
    '        X, y, epochs=EPOCHS, batch_size=BATCH_SIZE,\n'
    '        validation_split=0.15, callbacks=callbacks\n'
    '    )\n'
    '    # Training result: val_accuracy = 0.9460 (94.6%) at epoch 78\n'
    '    print(f"Best val_accuracy: {max(history.history[\'val_accuracy\']):.4f}")'
)
body('[INSERT SCREENSHOT HERE — Caption: Training log terminal output showing epoch 78 val_accuracy=0.9460 and final model saved as sign_language.h5 with 40 classes]')

# ── 6.7 isign_retrieval.py ────────────────────────────────────────────────────
subhead("6.7 isign_retrieval.py — Embedding and Cosine Similarity Query")
body(
    'isign_retrieval.py manages the 132 MB cosine similarity index '
    '(isign_retrieval_index.npz) built from the 14,674 iSign video clip embeddings '
    'across 101 phrase folders. At startup, ensure_isign_retrieval_index() loads the '
    'numpy compressed archive into memory. The query_index() function converts a raw '
    '30-frame landmark sequence to a mean-pooled 258-dimensional embedding, computes '
    'cosine similarity against all stored embeddings, and returns the top-k matching '
    'clip metadata (phrase label, video URL, similarity score). This powers both the '
    'ISL dictionary search and the sign recognition fallback when LSTM confidence '
    'is below the configured threshold.'
)
code_block(
    'import numpy as np, os\n'
    'from typing import List, Dict\n'
    '\n'
    'DEFAULT_INDEX_PATH = "isign_retrieval_index.npz"\n'
    'DEFAULT_META_PATH  = "isign_retrieval_meta.json"\n'
    '\n'
    '_index_embeddings = None    # shape (N, 258) float32\n'
    '_index_meta       = []      # list of {phrase, clip_id, url}\n'
    '\n'
    'def ensure_isign_retrieval_index(index_path: str, meta_path: str) -> bool:\n'
    '    """Load the 132 MB isign_retrieval_index.npz into memory."""\n'
    '    global _index_embeddings, _index_meta\n'
    '    if _index_embeddings is not None:\n'
    '        return True\n'
    '    if not os.path.exists(index_path):\n'
    '        print(f"WARN: iSign retrieval index not found at {index_path}")\n'
    '        return False\n'
    '    data = np.load(index_path, allow_pickle=False)\n'
    '    _index_embeddings = data["embeddings"].astype(np.float32)  # (N, 258)\n'
    '    import json\n'
    '    with open(meta_path, "r") as f:\n'
    '        _index_meta = json.load(f)\n'
    '    print(f"INFO: iSign index loaded — {len(_index_meta)} clips, "\n'
    '          f"embeddings shape {_index_embeddings.shape}")\n'
    '    return True\n'
    '\n'
    'def sequence_to_embedding(sequence: np.ndarray) -> np.ndarray:\n'
    '    """Mean-pool a (30, 258) sequence to a 258-dim embedding vector.\n'
    '       Normalise to unit length for cosine similarity computation.\n'
    '    """\n'
    '    emb = sequence.mean(axis=0).astype(np.float32)  # (258,)\n'
    '    norm = np.linalg.norm(emb)\n'
    '    return emb / (norm + 1e-8)\n'
    '\n'
    'def query_index(sequence: np.ndarray, top_k: int = 5) -> List[Dict]:\n'
    '    """Compute cosine similarity and return top-k matches.\n'
    '       Returns list of {phrase, url, similarity} sorted by similarity desc.\n'
    '    """\n'
    '    if _index_embeddings is None:\n'
    '        return []\n'
    '    query_vec = sequence_to_embedding(sequence)            # (258,)\n'
    '    # Dot product with pre-normalised index embeddings = cosine similarity\n'
    '    sims = _index_embeddings @ query_vec                   # (N,)\n'
    '    top_idx = np.argsort(sims)[::-1][:top_k]\n'
    '    return [\n'
    '        {**_index_meta[i], "similarity": float(sims[i])}\n'
    '        for i in top_idx\n'
    '    ]'
)
body('[INSERT SCREENSHOT HERE — Caption: ISL Dictionary page showing search query "hello", retrieved top-3 matching iSign clips with similarity scores (0.94, 0.91, 0.87) and clip thumbnails displayed]')

# ── 6.8 sign.js ───────────────────────────────────────────────────────────────
subhead("6.8 sign.js — TF.js Load, MediaPipe Extract, 30-Frame Buffer, Classify")
body(
    'sign.js (~1,600 lines) is the complete browser-side ML pipeline. On page load, '
    'it initialises MediaPipe Holistic and loads the TF.js LSTM model bundle from '
    '/static/models/tfjs_lstm/model.json. During animation frame callbacks, it extracts '
    '258-dimensional landmark vectors from each webcam frame, buffers the last 30 vectors '
    'in a circular array, runs TF.js prediction when the buffer is full, applies per-class '
    'confidence thresholds, and displays the result. A minimum-motion filter prevents '
    'static-hand false positives by checking landmark velocity across consecutive frames.'
)
code_block(
    '// sign.js — Browser-side LSTM sign recognition pipeline\n'
    '// Part of Samvak (Multi-Lingual Sign Language Translator)\n'
    '\n'
    'const SEQUENCE_LENGTH = 30;    // frames per prediction window\n'
    'const FEATURE_SIZE    = 258;   // 33*4 pose + 21*3 left + 21*3 right\n'
    'const CONFIDENCE_THR  = 0.70;  // minimum confidence to accept prediction\n'
    'const MIN_MOTION      = 0.002; // minimum landmark velocity to trigger inference\n'
    '\n'
    'let tfModel   = null;          // TF.js LayersModel\n'
    'let holistic  = null;          // MediaPipe Holistic instance\n'
    'let labels    = [];            // 40 ISL class label strings\n'
    'let frameBuffer = [];          // circular buffer of 258-dim Float32Arrays\n'
    '\n'
    'async function loadModel() {\n'
    '  // Load TF.js LSTM from tfjs_lstm/model.json\n'
    '  tfModel = await tf.loadLayersModel("/static/models/tfjs_lstm/model.json");\n'
    '  const res = await fetch("/static/models/tfjs_lstm/labels.json");\n'
    '  labels = await res.json();   // 40 ISL class strings\n'
    '  console.log(`LSTM loaded: ${labels.length} classes, ` +\n'
    '              `input (1, ${SEQUENCE_LENGTH}, ${FEATURE_SIZE})`);\n'
    '}\n'
    '\n'
    'function extractFeatures(results) {\n'
    '  // Extract 258-dim vector from MediaPipe Holistic results\n'
    '  function landmarks(lmList, count, dims) {\n'
    '    const vec = new Array(count * dims).fill(0);\n'
    '    if (lmList) {\n'
    '      lmList.slice(0, count).forEach((lm, i) => {\n'
    '        vec[i * dims]     = lm.x;\n'
    '        vec[i * dims + 1] = lm.y;\n'
    '        vec[i * dims + 2] = lm.z;\n'
    '        if (dims === 4) vec[i * dims + 3] = lm.visibility || 0;\n'
    '      });\n'
    '    }\n'
    '    return vec;\n'
    '  }\n'
    '  const pose  = landmarks(results.poseLandmarks,       33, 4); // 132\n'
    '  const lhand = landmarks(results.leftHandLandmarks,   21, 3); // 63\n'
    '  const rhand = landmarks(results.rightHandLandmarks,  21, 3); // 63\n'
    '  return new Float32Array([...pose, ...lhand, ...rhand]);       // 258\n'
    '}\n'
    '\n'
    'async function onResults(results) {\n'
    '  const features = extractFeatures(results);  // Float32Array(258)\n'
    '\n'
    '  // Motion filter: skip near-static frames\n'
    '  if (frameBuffer.length > 0) {\n'
    '    const last = frameBuffer[frameBuffer.length - 1];\n'
    '    const motion = features.reduce((sum, v, i) =>\n'
    '      sum + Math.abs(v - last[i]), 0) / FEATURE_SIZE;\n'
    '    if (motion < MIN_MOTION) return;\n'
    '  }\n'
    '\n'
    '  frameBuffer.push(features);\n'
    '  if (frameBuffer.length > SEQUENCE_LENGTH)\n'
    '    frameBuffer.shift();  // circular buffer\n'
    '\n'
    '  if (frameBuffer.length === SEQUENCE_LENGTH && tfModel) {\n'
    '    // Build (1, 30, 258) tensor and run inference\n'
    '    const flat   = new Float32Array(SEQUENCE_LENGTH * FEATURE_SIZE);\n'
    '    frameBuffer.forEach((f, i) => flat.set(f, i * FEATURE_SIZE));\n'
    '    const tensor = tf.tensor3d(flat, [1, SEQUENCE_LENGTH, FEATURE_SIZE]);\n'
    '    const probs  = tfModel.predict(tensor);   // shape (1, 40)\n'
    '    const data   = await probs.data();        // Float32Array of 40 probs\n'
    '    tensor.dispose();  probs.dispose();\n'
    '\n'
    '    const idx        = data.indexOf(Math.max(...data));\n'
    '    const confidence = data[idx];\n'
    '    if (confidence >= CONFIDENCE_THR) {\n'
    '      const label = labels[idx];\n'
    '      displayPrediction(label, confidence);\n'
    '      sendToFlask(label, confidence);  // POST /sign/predict for translation+TTS\n'
    '    }\n'
    '  }\n'
    '}'
)
body('[INSERT SCREENSHOT HERE — Caption: Browser DevTools console showing TF.js LSTM model loaded successfully with "40 classes, input (1, 30, 258)" message and MediaPipe Holistic initialised, with live webcam feed visible in background]')

# ── 6.1 Modules ────────────────────────────────────────────────────────────────
subhead("6.1 Module Descriptions")
body(
    'Saṁvāk is structured around six primary functional modules, each encapsulating '
    'a distinct domain of responsibility:'
)
body(
    '1. Sign Recognition Module (sign.py + sign.js + tfjs_lstm/): Handles the complete '
    'sign-to-text pipeline from webcam frame capture through MediaPipe landmark extraction '
    '(258D per frame), 30-frame buffer management, TF.js LSTM browser inference, and '
    'server-side validation. Sub-modules include the geometry-based fallback classifier '
    '(geometry_brain.py, 27,695 bytes) for static hand configurations and the '
    'fingerspelling recogniser (fingerspell_recognizer.py, 6,743 bytes) for letter-by-letter '
    'spelling of unrecognised words.'
)
body(
    '2. Speech Processing Module (speech.py + grammar_helper.py): Manages the speech-to-sign '
    'pipeline including audio upload handling, format conversion (WebM → WAV via pydub), '
    'Google STT transcription via SpeechRecognition, ISL grammar transformation via '
    'grammar_helper.py local engine and Google Gemini API, and gTTS audio synthesis. '
    'The module returns both ISL gloss token arrays for avatar animation and audio URLs '
    'for text-to-speech playback.'
)
body(
    '3. Authentication Module (auth.py, 4,834 bytes): Implements user registration with '
    'bcrypt password hashing, login with Flask-Login session management, profile update, '
    'preferences storage, and secure logout. All authentication routes are protected by '
    'CSRF validation and rate limiting.'
)
body(
    '4. ISL Dictionary Module (dictionary.py, 7,133 bytes + isign_retrieval.py, 9,530 bytes): '
    'Provides a searchable ISL phrase dictionary powered by the 132 MB cosine similarity '
    'retrieval index (isign_retrieval_index.npz) over the 14,674-clip iSign dataset. Users '
    'can search by English phrase, browse by category, and view matching ISL sign video '
    'clips ordered by similarity score.'
)
body(
    '5. Learning Module (learn/ templates + XP): Implements the gamified learning experience '
    'with XP-based progress tracking stored in UserProgress (SQLite). Users earn 10 XP per '
    'new sign learned and 2 XP for practice repetitions. The dashboard displays total XP, '
    'current level (100 XP per level), and unique signs learned count.'
)
body(
    '6. 3D Avatar Module (sign.js Three.js integration, model_assets.py, 36,050 bytes): '
    'Renders the humanoid ISL signing avatar using Three.js r128 with WebGL. Joint angle '
    'keyframe animations are pre-computed for each ISL sign token. The avatar module '
    'accepts an array of gloss tokens and plays them sequentially with configurable '
    'timing speed (1.0× default, adjustable in user preferences). Unknown tokens trigger '
    'fingerspelling animation via individual letter sign sequences.'
)
body('[INSERT SCREENSHOT HERE — Caption: Saṁvāk dashboard showing user stats panel (XP: 340, Level: 4, Words Learned: 28) with navigation to all six modules visible in the sidebar]')

# ── Save checkpoint ──
doc.save(OUT)
print(f"Chapter 6 (Code + Modules) saved: {OUT}")
